//LOCALHOST
## Get all contacts
GET http://localhost:3000/contacts

### GET Contact by id
GET http://localhost:3000/contacts/59b99db4cfa9a34dcd7885b6

### Create contact
POST http://locathost:3000/contacts HTTP/1.1
content-type: application/json

{
    "email": "sean_bean@gameofthron.es",
    "birthday": "7 June 1994",
    "favoriteColor": "Blue ",
    "firstName": "Ned Stark",
    "lastName": "Stark"
}

### PUT contact
POST http://locathost:3000/contacts/59b99dbecfa9a34dcd7885ca HTTP/1.1
content-type: application/json

{
    "email": "john_bradley-west@gameofthron.es",
    " favoriteColor": "black",
    " firstName": "Samwell ",
    " lastName": "Tarly",
    "birthday": "17 May 1994"
}

### DELETE contact
DELETE Hhttp://localhost:3000/contacts/